services:
  java-app:
    build: .
    hostname: java-app
    ports:
      - "8085:8080"
    environment:
      - "JAVA_OPTS=-Xms128m -Xmx512m"
    volumes:
      - type: volume
        source: maven-repo-cache
        target: /root/.m2

volumes:
  maven-repo-cache:
